channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - gcc
  - gxx
  - pip:
      - setuptools
      - wheel
      - tqdm==4.64.0
      - numpy
      - MDAnalysis
      - torch
      - cmdstanpy
