# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors:     James Krieger (jmkrieger@cnb.csic.es)
# *
# * Centro Nacional de Biotecnologia, CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************


"""
This module will estimate weights using MCMC
"""
import numpy as np
import os

from pwem.protocols import EMProtocol
from pwem.objects import EMSet, EMObject, EMFile

from pyworkflow.protocol import params
from pyworkflow.object import Float, String

import reweighting
from reweighting.constants import (REWEIGHTING_SCRIPTS, 
                                   REWEIGHTING_MEAN, REWEIGHTING_STD)

class ReweightingEstimateWeightsProtocol(EMProtocol):
    """
    Estimates statistical weights for structural classes or states by combining
    prior cluster-size information with particle-to-reference likelihood or
    distance data through Markov Chain Monte Carlo sampling. The protocol is
    intended for reweighting heterogeneous cryo-EM ensembles, where the goal is
    not only to compare structural populations but also to infer corrected
    posterior occupancies that better reflect the experimental image evidence.

    AI Generated:

    Estimate Weights (ReweightingEstimateWeightsProtocol) — User Manual
        Overview

        The Estimate Weights protocol computes posterior weights for a set of
        structural classes, conformations, or reference states by integrating
        two complementary sources of information. The first is an initial prior
        estimate of class occupancy, typically derived from cluster sizes or
        previously assigned populations. The second is a collection of
        particle-based log-likelihood or distance measurements that quantify how
        well each experimental particle agrees with each candidate state.

        In practical cryo-EM analysis, this protocol becomes especially useful
        when the original class populations are suspected to be biased by
        classification artifacts, unequal sampling, or limited reconstruction
        sensitivity. Rather than relying only on raw cluster counts, the method
        refines those populations probabilistically using image evidence,
        producing a more robust estimate of the relative abundance of each
        structural state.

        Inputs and General Workflow

        The protocol accepts prior cluster-size information either from an
        external file or from a Scipion object containing weighted items such as
        classes, volumes, trajectory frames, or atomic structures. When weights
        are available as attributes, they are used directly. Otherwise, uniform
        initial populations are assumed. The protocol automatically normalizes
        these values so that they form a proper probability distribution before
        inference begins.

        Image-based evidence can also be imported in two ways. Users may provide
        precomputed files directly from disk, or they may point to one or more
        particle sets containing per-particle log-likelihood values generated by
        previous scoring protocols. When particle sets are used, the protocol
        reshapes the data into matrices whose rows correspond to structural
        states and whose columns correspond to particles.

        In some biological applications, the absolute magnitude of likelihood
        values is less informative than relative differences across states. For
        that reason, the protocol optionally supports mean-subtracted
        log-likelihood matrices, which often improve interpretability and reduce
        biases caused by global offsets.

        Bayesian Inference by MCMC

        Once the input priors and likelihood matrices have been prepared, the
        protocol launches a Markov Chain Monte Carlo inference procedure. This
        step estimates the posterior distribution of class weights rather than a
        single deterministic solution. Multiple chains can be used to improve
        sampling robustness, and both warm-up and sampling lengths can be tuned
        depending on the complexity of the system.

        From a biological perspective, this sampling framework is important
        because conformational landscapes are rarely described by exact single
        values. Instead, the protocol captures uncertainty in the estimated
        occupancies, which is often critical when comparing subtle
        conformational differences, low-population intermediates, or noisy
        datasets.

        The optional lambda parameter controls normalization of image evidence.
        In most workflows based directly on log-likelihood values, the default
        setting is appropriate and no further normalization is required.

        Parallel Execution and Practical Considerations

        The protocol supports parallel execution by distributing independent
        chains and threads across available computational resources. This is
        especially valuable for large datasets or models containing many
        structural states, where posterior sampling may otherwise become
        computationally expensive.

        Choosing the number of chains, warm-up iterations, and sampling
        iterations should depend on the expected complexity of the biological
        landscape. Simple systems with clearly separated states may converge
        rapidly, whereas highly heterogeneous ensembles may require longer
        sampling to obtain stable posterior estimates.

        Outputs and Interpretation

        After inference, the protocol computes the posterior mean and posterior
        standard deviation for each structural state. If the input originated
        from a Scipion object, the output preserves the original object
        identity while appending the estimated mean weight and uncertainty to
        each item. If no structural object is available, a generic output set is
        created containing one item per inferred state.

        Biologically, the posterior mean represents the best estimate of the
        relative population of each state after integrating prior information
        with particle evidence. The posterior standard deviation provides an
        uncertainty estimate that is often just as important as the mean itself.
        Large uncertainty may indicate insufficient image evidence, overlapping
        structural classes, or intrinsic ambiguity in the conformational
        landscape.

        Practical Interpretation

        In routine cryo-EM ensemble analysis, this protocol is most useful when
        the goal is not merely classification but quantitative interpretation of
        population distributions. It can help determine whether apparently minor
        classes are truly underpopulated or whether they become more relevant
        once particle evidence is taken into account.

        This makes the protocol particularly valuable for studying continuous
        motions, rare intermediate states, ligand-induced conformational shifts,
        or any biological system where population balance carries mechanistic
        meaning.

        Final Perspective

        For biological users, this protocol transforms classification-derived
        populations into statistically grounded occupancy estimates. By combining
        prior structural populations with direct particle evidence, it provides a
        principled way to infer ensemble composition together with uncertainty.
        In heterogeneous cryo-EM studies, this often leads to more reliable
        biological interpretation than relying on raw class sizes alone.
    """
    _label = 'Estimate weights'

    IMPORT_FROM_FILES = 0
    USE_POINTER = 1

    # -------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        """ Define the input parameters that will be used.
        Params:
            form: this is the form to be populated with sections and params.
        """
        # You need a params to belong to a section:
        form.addParallelSection(threads=1, mpi=0)

        form.addSection(label='Inputs')

        form.addParam('infileClusterSizeData', params.EnumParam, choices=['file', 'pointer'],
                      label="Import initial cluster sizes from",
                      default=self.USE_POINTER,
                      display=params.EnumParam.DISPLAY_HLIST,
                      help='Import cluster sizes from local file or Scipion object')
        form.addParam('clusterSizeFile', params.PathParam, label="File path",
                      condition='infileClusterSizeData == IMPORT_FROM_FILES',
                      allowsNull=True,
                      help='Specify a path to desired cluster sizes file.')
        form.addParam('clusterSizePointer', params.PointerParam, 
                      label="Cluster size object",
                      condition='infileClusterSizeData == USE_POINTER',
                      pointerClass='SetOfAtomStructs,SetOfTrajFrames,SetOfVolumes,SetOfClassesTraj',
                      help='The input structures can be any set that contains sizes')
        
        form.addParam('infileImageDistanceData', params.EnumParam, choices=['file', 'pointer'],
                      label="Import log likelihood or distances from",
                      default=self.USE_POINTER,
                      display=params.EnumParam.DISPLAY_HLIST,
                      help='Import cluster sizes from local file or Scipion object')

        form.addParam('filesPath', params.PathParam,
                      condition="infileImageDistanceData == IMPORT_FROM_FILES",
                      label="Files directory",
                      help="Directory with the files you want to import.\n\n"
                           "The path can also contain wildcards to select"
                           "from several folders. \n\n"
                           "Examples:\n"
                           "  ~/project/data/day??_files/\n"
                           "Each '?' represents one unknown character\n\n"
                           "  ~/project/data/day*_files/\n"
                           "'*' represents any number of unknown characters\n\n"
                           "  ~/project/data/day##_files/\n"
                           "'##' represents two digits that will be used as "
                           "file ID\n\n"
                           "NOTE: wildcard characters ('*', '?', '#') "
                           "cannot appear in the actual path.)")

        form.addParam('filesPattern', params.StringParam,
                      label='File pattern',
                      condition="infileImageDistanceData == IMPORT_FROM_FILES",
                      help="Pattern of the files to be imported.\n\n"
                           "The pattern can contain standard wildcards such as\n"
                           "*, ?, etc, or special ones like ### to mark some\n"
                           "digits in the filename as ID.\n\n"
                           "NOTE: wildcards and special characters" 
                           "('*', '?', '#', ':', '%') cannot appear in the actual path.\n\n")

        form.addParam('imageDistancePointers', params.MultiPointerParam, 
                      label="Image distance object(s)",
                      condition='infileImageDistanceData == USE_POINTER',
                      pointerClass='EMFile,SetOfParticles',
                      help='This can be the output from a distance calculation job')
        
        form.addParam('useSubLL', params.BooleanParam, default=False,
                      condition='infileImageDistanceData == USE_POINTER',
                      label="Use mean-subtracted log likelihood",
                      pointerClass='EMFile,SetOfParticles')

        form.addParam('chains', params.IntParam, default=4,
                      label="Number of MCMC chains",
                      help='Number of chains for Markov Chain Monte Carlo for posterior sampling')
        
        form.addParam('iterwarmup', params.IntParam, default=200,
                      label="Number of warm up iterations",
                      help='Number of MCMC warm up steps')
        
        form.addParam('itersample', params.IntParam, default=2000,
                      label="Number of sample iterations",
                      help='Number of MCMC sample steps')
        
        form.addParam('parallelchain', params.IntParam, default=1,
                      label="Number of chains in parallel",
                      help='(for parallelization) number of chains in parallel for MCMC')

        form.addParam('lambda_', params.FloatParam, default=-1,
                      label="Noise standard deviation lambda",
                      expertLevel=params.LEVEL_ADVANCED,
                      help='Leave it as -1 if using logLikelihood to not normalise with lambda again')  

    # --------------------------- STEPS functions ------------------------------
    def _insertAllSteps(self):
        # Insert processing steps
        self._insertFunctionStep('convertInputStep')
        self._insertFunctionStep('calculationStep')
        self._insertFunctionStep('createOutputStep')

    def convertInputStep(self):

        if self.infileClusterSizeData.get() == self.IMPORT_FROM_FILES:
            self.infileclustersize = self.clusterSizeFile.get()
        else:
            clusterSizeObject = self.clusterSizePointer.get()
            if hasattr(clusterSizeObject.getFirstItem(), '_weights'):
                self.clusterSizes = [item._weights.get() for item in clusterSizeObject]
            elif hasattr(clusterSizeObject.getFirstItem(), '_prodyWeights'):
                self.clusterSizes = [item._prodyWeights.get() for item in clusterSizeObject]
            else:
                self.clusterSizes = np.ones(len(clusterSizeObject))

            if isinstance(self.clusterSizes, list):
                self.clusterSizes = np.array(self.clusterSizes)

            if self.clusterSizes.sum() != 1:
                self.clusterSizes /= self.clusterSizes.sum()

            self.infileclustersize = self._getExtraPath('cluster_sizes.txt')
            np.savetxt(self.infileclustersize, self.clusterSizes)

        if self.infileImageDistanceData.get() == self.IMPORT_FROM_FILES:
            infileimagedistance = self.getMatchFiles()
        else:
            infileimagedistance = []
            for i, pointer in enumerate(self.imageDistancePointers):
                distanceObject = pointer.get()
                if isinstance(distanceObject, EMFile):
                    filename = distanceObject.getFileName()
                else:
                    if hasattr(distanceObject.getFirstItem(), '_xmipp_logLikelihood'):
                        imageDistances = np.array([particle._xmipp_logLikelihood.get() for particle in distanceObject])
                    elif hasattr(distanceObject.getFirstItem(), '_cryolike_logLikelihood'):
                        imageDistances = np.array([particle._cryolike_logLikelihood.get() for particle in distanceObject])

                    imageDistances = imageDistances.reshape((len(self.clusterSizes),-1))

                    if self.useSubLL:
                        imageDistances = np.subtract(imageDistances, np.mean(imageDistances, axis=0))

                    filename = self._getExtraPath('image_distances_{0}.npy'.format(i+1))
                    np.save(filename, imageDistances)

                infileimagedistance.append(filename)
            
        self.infileimagedistance = " ".join(infileimagedistance)

    def calculationStep(self):

        params = (self.infileclustersize, self.infileimagedistance, 
                  self._getExtraPath(),
                  self.chains.get(), self.iterwarmup.get(),
                  self.itersample.get(), self.lambda_.get())

        command = "python3 -m cryoER.run_cryoER_mcmc"
        args = """--infileclustersize {0} --infileimagedistance {1} --outdir \
{2} --chains {3} --iterwarmup {4} --itersample {5} --lmbd {6}""".format(*params)
        
        parallelChains = self.parallelchain.get()
        threadsPerChain = int(self.numberOfThreads.get()/parallelChains)
        if parallelChains > 1 or threadsPerChain > 1:
            args += " --parallelchain {0} --threadsperchain {1}".format(parallelChains, 
                                                                        threadsPerChain)

        self.runJob(reweighting.Plugin.getReweightingCmd(command), args)

        command2 = "python3 " + os.path.join(REWEIGHTING_SCRIPTS, "analyse.py")
        args2 = "--output_directory {0} --filename_cluster_counts {1}".format(self._getExtraPath(),
                                                                              self.infileclustersize)
        self.runJob(reweighting.Plugin.getReweightingCmd(command2), args2)

    def createOutputStep(self):
        # register output files
        self.args = {}

        self.means = np.loadtxt(self._getExtraPath("reweighting_mean_weights.txt"))
        self.stds = np.loadtxt(self._getExtraPath("reweighting_std_weights.txt"))

        inSet = self.clusterSizePointer.get()
        if inSet is not None:
            inputClass = type(inSet)
            self.idxMap = sorted(list(inSet.getIdSet()))
            outSet = inputClass().create(self._getExtraPath())
            outSet.copyItems(inSet, updateItemCallback=self._addWeights)
        else:
            outSet = EMSet().create(self._getExtraPath())
            self.idxMap = []
            for i, _ in enumerate(self.means):
                self.idxMap.append(i)
                item = EMObject()
                self._addWeights(item)
                outSet.append(item)

        self.args["outputSet"] = outSet
        self._defineOutputs(**self.args)

    def _addWeights(self, item, row=None):
        idx = self.idxMap.index(item.getObjId())

        # We provide data directly so don't need a row
        mean = Float(self.means[idx])
        mean.setPrecision(1e-6)
        setattr(item, REWEIGHTING_MEAN, mean)

        std = Float(self.stds[idx])
        std.setPrecision(1e-6)
        setattr(item, REWEIGHTING_STD, std)

    # --------------------------- INFO functions -----------------------------------
    def _summary(self):
        """ Summarize what the protocol has done"""
        summary = []
        if self.isFinished():
            summary.append("This protocol has finished.")
        return summary

    def _methods(self):
        methods = []
        if self.isFinished():
            methods.append("This protocol has printed methods")
        return methods

    def _validate(self):
        errors = []
        for i, pointer in enumerate(self.imageDistancePointers):
            distanceObject = pointer.get()
            if not isinstance(distanceObject, EMFile):
                if not (hasattr(distanceObject.getFirstItem(), '_xmipp_logLikelihood')
                        or hasattr(distanceObject.getFirstItem(), '_cryolike_logLikelihood')):
                    errors.append('The input particle set {0} must have xmipp or cryolike logLikelihood data'.format(i+1))

        return errors